version: '3'
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - internal
      - players
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server:/app/server
    environment:
      - MONGO_URL=mongodb://db:27017/odyssey-test
      - DOCKER_NETWORK=linux-odyssey-players
  db:
    image: mongo
    restart: always
    networks:
      - internal
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  swagger:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 8080:8080
    volumes:
      - ./server/swagger.yaml:/tmp/swagger.yaml
    environment:
      - SWAGGER_FILE=/tmp/swagger.yaml

networks:
  internal:
  players:
    name: linux-odyssey-players
