id: get-started
image: base
title: 輸入指令
instruction: |
  歡迎來到終端機的世界！
  這個關卡是為了讓你熟悉終端機的基本操作。
  在這個關卡中，你將會學到：
  1. 如何使用這個網站
  2. 如何使用終端機
  3. 如何使用 `echo` 指令

stages:
  - id: start
    name: 按下 `開始` 按鈕開始
    condition:
      command: ^echo start$
    response:
      content: |
        終端機是一個讓你可以直接和電腦「對話」的工具。你可以在終端機裡輸入指令，電腦就會根據你的指令執行動作。這裡不像點擊按鈕那樣操作，而是用文字來告訴電腦你想做什麼。

        現在，請你在終端機輸入第一個指令：`echo hello`，然後按下 Enter。這個指令會讓終端機顯示出「hello」這個字，試試看吧！

  - id: echo-hello
    name: 在終端機輸入 `echo hello`
    requirements:
      - start
    condition:
      command: ^echo hello$
    response:
      content: |
        恭喜你完成了你的第一個指令！
        你應該可以看到終端機上顯示了以下內容：
        ```
        commander:~ $ echo hello
        hello
        ```
        看到 `commander:~ $` 的時候，代表電腦在等你輸入指令。
        當你輸入 `echo hello` 後，電腦就會在下一行回答「hello」。

        指令就像是告訴電腦要做什麼的句子。
        就像 `echo hello` 這個指令：
        - `echo` 是在告訴電腦「請你說出」
        - `hello` 是要電腦說的內容
        所以當你輸入 `echo hello` 時，電腦就會說出「hello」。

        好的，那接下來，請你試試讓終端機顯示 `hello NPC` 這個字串。
        如果遇到困難，可以按下 `提示` 按鈕來獲得提示。
      hint: |
        請輸入 `echo hello NPC` 來繼續下一個步驟。

  - id: echo-NPC
    name: 在終端機輸入 `echo hello NPC`
    requirements:
      - echo-hello
    condition:
      command: ^echo hello [Nn][Pp][Cc]$
    response:
      content: |
        恭喜你學會了如何使用 `echo` 指令。
        你可能會好奇，為什麼我們需要有這樣的指令。
        雖然 `echo` 指令是個很簡單的指令，但它卻是許多指令的基礎。
        在我們的冒險中，也常會使用 `echo` 指令來觸發事件。
        那麼我們這個關卡就到此為止，請你輸入 `echo finish` 來結束這個關卡。

  - id: END
    name: 結束關卡
    requirements:
      - echo-NPC
    condition:
      command: ^echo finish$
    response:
      content: |
        恭喜你，你已經完成了這個關卡！
        你已經學會了如何使用 `echo` 指令，並且了解了它的用途。
