id: checkpoint-02
title: 分類社課資料
image: base
instruction: |
  這是第二個測驗關卡！

  緊急任務！社團的檔案管理員不小心把所有社課檔案都丟在同一個資料夾裡了！
  
  你需要幫忙把這些檔案分類到正確的資料夾中。

requirements:
  - tab
  - move


stages:
  - id: start
    name: 按下 `開始` 按鈕開始整理任務
    condition:
      command: echo start
    response:
      content: |
        😱 糟糕！所有的社課檔案都混在一起了！
        
        "拜託大家幫忙整理一下，下週就要開始上課了，
        如果檔案沒有分類好，社員們會找不到教材的！"
        
        請先查看目前資料夾的內容，看看有哪些檔案需要整理。


  - id: ls-messy
    name: 查看目前資料夾的內容
    requirements:
      - start
    condition:
      command: ls
    response:
      content: |
        天啊！檔案真的很亂呢！你看到了各種檔案混在一起，

        請先創建三個目標資料夾：python、web、c
        請根據檔名判斷每個檔案應該放到哪個資料夾。
        每個分類都有程式碼檔案和課程大綱檔案。
        如果不確定的話，可以用 `cat` 查看檔案內容來幫助判斷。
        
        請開始整理這些檔案吧！

        💡 提示：若是檔案亂掉，可以按左下角的 `重來` 按鈕來重置關卡。

  - id: classify-files
    name: 將所有檔案分類到正確的資料夾
    requirements:
      - ls-messy
    condition:
      files:
        - path: /home/commander/python/calculator.py
          type: file
          exists: true
        - path: /home/commander/python/python_syllabus.txt
          type: file
          exists: true
        - path: /home/commander/web/portfolio.html
          type: file
          exists: true
        - path: /home/commander/web/main.css
          type: file
          exists: true
        - path: /home/commander/web/web_syllabus.txt
          type: file
          exists: true
        - path: /home/commander/c/hello.c
          type: file
          exists: true
        - path: /home/commander/c/c_syllabus.txt
          type: file
          exists: true
    response:
      content: |
        🎉 太棒了！看起來所有檔案都分類完成了！
        
        謝謝你的幫忙！現在所有的社課檔案都井井有條了：
        - python/ 資料夾：Python程式設計檔案和課程大綱
        - web/ 資料夾：網頁設計檔案和課程大綱
        - c/ 資料夾：C語言程式檔案和課程大綱
        
        這樣社員們就能輕鬆找到需要的教材了！

        輸入`echo finish` 完成任務吧！
        


  - id: finish
    name: 輸出 `finish` 完成任務
    requirements:
      - classify-files
    condition:
      command: echo finish
    response:
      content: |
        🏆 恭喜你完成了檔案分類任務，展現了優秀的檔案管理能力！