name: Production Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  ci-checks:
    uses: ./.github/workflows/ci-checks.yml

  build:
    needs: ci-checks
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and update service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
