name: Pull Request Workflow

on:
  pull_request:

jobs:
  ci-checks:
    uses: ./.github/workflows/ci-checks.yml

  code_review:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.4-alpha
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-4-1106-preview'
          GITHUB_TOKEN: ${{ github.token }}

  build:
    uses: ./.github/workflows/build.yml
    needs: ci-checks
