name: Pull Request Workflow

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    uses: ./.github/workflows/ci-checks.yml

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
