name: Pull Request Workflow

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    uses: ./.github/workflows/ci-checks.yml
    secrets: inherit

  code_review:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-4-1106-preview'
          GITHUB_TOKEN: ${{ github.token }}

  build:
    needs: ci-checks
    uses: ./.github/workflows/build.yml
    secrets: inherit
